import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: ["intro", "quick-start", "tutorial"],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "core/resources-and-app",
        "core/crud",
        "core/filtering",
        "core/pagination",
        "core/aggregations",
        "core/relations",
        "core/search",
        "core/batch",
        "core/soft-delete",
        "core/fields",
        "core/optimistic-locking",
        "core/procedures",
        "core/nested-writes",
      ],
    },
    {
      type: "category",
      label: "Real-time",
      items: [
        "realtime/subscriptions",
        "realtime/aggregate-subscriptions",
        "realtime/changelog",
        "realtime/mutation-tracking",
      ],
    },
    {
      type: "category",
      label: "Authentication & Security",
      items: [
        "auth/overview",
        "auth/sessions",
        "auth/jwt",
        "auth/oidc-provider",
        "auth/federated",
        "auth/api-keys",
        "auth/mfa",
        "auth/magic-links",
        "auth/passwords",
        "auth/account-security",
        "auth/scopes",
        "auth/secure-queries",
        "auth/security-headers",
      ],
    },
    {
      type: "category",
      label: "Platform Services",
      items: [
        "platform/storage",
        "platform/email",
        "platform/billing",
        "platform/tasks",
        "platform/kv",
        "platform/health",
      ],
    },
    {
      type: "category",
      label: "Client Library",
      items: [
        "client/overview",
        "client/queries",
        "client/react-hooks",
        "client/live-queries",
        "client/offline",
        "client/auth",
        "client/files",
        "client/billing",
        "client/typegen",
        "client/react-native",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        "deployment/node",
        "deployment/workers",
        "deployment/databases",
        "deployment/durable-object-kv",
        "deployment/environment-variables",
      ],
    },
    {
      type: "category",
      label: "Tooling",
      items: [
        "tooling/cli",
        "tooling/openapi",
        "tooling/admin-ui",
        "tooling/middleware",
        "tooling/error-handling",
      ],
    },
    {
      type: "category",
      label: "Migration",
      items: ["migration/from-express"],
    },
    {
      type: "category",
      label: "Contracts (Invariants)",
      items: [
        "contracts/overview",
        "contracts/auth",
        "contracts/billing",
        "contracts/email",
        "contracts/environment-variables",
        "contracts/etag",
        "contracts/offline-sync",
        "contracts/pagination",
        "contracts/search",
        "contracts/storage",
        "contracts/subscriptions",
        "contracts/tasks",
        "contracts/track-mutations",
      ],
    },
  ],
};

export default sidebars;
